AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Classroom Sessions API

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        TABLE_NAME: ClassroomSessions
        DYNAMODB_ENDPOINT: http://host.docker.internal:8000
        AWS_REGION: local

Resources:
  ClassroomSessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ClassroomSessions
      AttributeDefinitions:
        - AttributeName: ClassRoomID
          AttributeType: S
        - AttributeName: SessionID
          AttributeType: S
        - AttributeName: CohortID
          AttributeType: S
        - AttributeName: Date
          AttributeType: S
      KeySchema:
        - AttributeName: ClassRoomID
          KeyType: HASH
        - AttributeName: SessionID
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: DateIndex
          KeySchema:
            - AttributeName: Date
              KeyType: HASH
            - AttributeName: ClassRoomID
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  ClassroomSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api_function/
      Handler: app.lambda_handler
      Runtime: python3.13
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ClassroomSessionsTable
      Architectures:
        - x86_64
      Events:
        GetSessionsByDate:
          Type: Api
          Properties:
            Path: /sessions/date
            Method: get
        GetSessionByClassroomAndDate:
          Type: Api
          Properties:
            Path: /classroom/{classroom_id}
            Method: get
        GetClassroomSessions:
          Type: Api
          Properties:
            Path: /classroom/{classroom_id}/sessions
            Method: get
        GetSessionById:
          Type: Api
          Properties:
            Path: /session/{session_id}
            Method: get

Outputs:
  ClassroomSessionsApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ClassroomSessionFunction:
    Description: Lambda Function ARN
    Value: !GetAtt ClassroomSessionFunction.Arn
  ClassroomSessionsTableName:
    Description: DynamoDB Table Name
    Value: !Ref ClassroomSessionsTable
